### ISSUE TITLE
AWS upload wizard should do a basic form validation

### ISSUE THREAD

**Issue by msehnout** [osbuild/cockpit-composer#1081]
The "region" value:
https://github.com/osbuild/cockpit-composer/blob/92a2330fc9a1b7101f63ea1ada653ba010bcf8e4/components/Wizard/AWSDestinationStep.js#L116

is used as part of a domain name. The form should perform at least a basic validation that will make sure the string is a valid DNS label.

Example error from osbuild-composer logs:
```
caused by: parse "https://s3.EU (Frankfurt).amazonaws.com/{Bucket}/{Key+}?uploads": invalid character " " in host name
```

More advanced form validation could use a list of valid AWS regions:
https://docs.aws.amazon.com/general/latest/gr/rande.html
This would have the disadvantage of becoming obsolete once Amazon adds a new zone.

**Comment by jkozol** [comment]
@msehnout Thanks for the suggestion. Do you think a validation such as checking the format is `[2 characters]-[string]-[digit]` is helpful? Any thoughts @jgiardino?

**Comment by jgiardino** [comment]
@msehnout When osbuild-composer returns an error, how does that validation happen?

Here are a few suggestions, starting with ideal behavior first, depending on what's possible and in scope. 
- Ideally, we would be able to pull the list of all valid regions, and list them in a select menu.
- Assuming there is no API call to return a list of all regions, the next best alternative is to list the ones we know about, and provide an option to manually type in any region that is added after this update is made. There's a [PF Select Typeahead component](https://www.patternfly.org/v4/documentation/react/components/select#typeahead) that provides this functionality, where the user can select a region from the list, or type to specify one not included in the list. 
  - In our case, we would want to use a string other than "Create" since the user isn't creating the region. Maybe "Use" is the right action in our case? 
  - Somewhere we should also mention how this control behaves. The PF example includes "Select a state" as placeholder text, but it might not be obvious to the user that if one is missing, they can type that in. Maybe a better placeholder for this case is something like "Type to filter the list or to specify a value that is missing from the list". But that's really long, so maybe it should also go somewhere else 🤷 Another variation that is shorter: "Filter the list or provide a new value"
  - This option still requires that we validate the region that the user enters manually, as mentioned next...
- If the Typeahead Select option is out of scope, then validating the regions as @jkozol suggests sounds reasonable. In that case, we would display an error message like, "The value you provided for region does not match the standard format of a region code." 
  - I'm on the fence about providing a link to the regions, though mostly am in favor of doing so. My main concern is we direct them to check the AWS documentation, and the page is no longer valid but I think the benefit outweighs the risk. If we decide to provide this link, we can provide an additional statement with the error text: "Codes for regional endpoints are listed in the [AWS documentation.](https://docs.aws.amazon.com/general/latest/gr/rande.html)"
  - It would also be beneficial to provide this link in the help text popover, and not wait to share it until they try and fail to provide a missing endpoint.

**Comment by msehnout** [comment]
> @msehnout Thanks for the suggestion. Do you think a validation such as checking the format is `[2 characters]-[string]-[digit]` is helpful? Any thoughts @jgiardino?

Yes, I think that would work.

> @msehnout When osbuild-composer returns an error, how does that validation happen?

There is unfortunately no validation at our side (osbuild-composer). The error comes from the HTTP client we use. We simply make HTTP request which fails on DNS lookup because the domain name from the URL contains forbidden characters.

Otherwise, @jgiardino , all your suggestions sound reasonable to me. If I were the user, I'd probably prefer the list of regions from which I would select the right one, but that is the hardest one to maintain. Simple validation and a link to the documentation should be enough.
