### ISSUE TITLE
Error handling in Create Recipe for duplicate names

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#115]
### Description of problem

In the Create Recipe modal, each time a character is entered in the recipe name field, an api call for the recipe list is made. Should we just make this api call once? Or should the list just be passed to the modal as a prop?

I understand there is a case where another user creates a recipe using the same name while the current user has this dialog open and is typing. But the current implementation doesn't fully handle this case (i.e. if user 1 and user 2 type the same name at the same time, and user 2 hits save first, what would happen with the current implementation?)

Getting the recipe list on each key press seems excessive, and I wonder if we should get it once on opening the dialog (or even just passed via props)? But regardless, we should definitely get the recipe list on save to double-check the name hasn't been used in between the time the user exited the name field and clicked Save.

### Component (web, API, etc)
Web

### Version or commit hash (if applicable)
Introduced in PR #114

### How often reproducible
Everytime

### Steps to Reproduce

1. On Recipes page, click Create Recipe
2. Open the terminal running the bdcs-api-rs 
3. Set focus in the name field and type a character

### Actual results
An api call for the list of recipes is made with each key press

### Expected results
An api call is made a minimum of 2 times, once on opening the dialog (or maybe just use props) and once on Save.

**Comment by KKoukiou** [comment]
This should be handled like this in the future:

The blueprints list should be updated dynamically with events, and this should be passed to the Modal as a property. Once it changes the property will change and the modal will re-render.
If the name we have inserted matches an existing name, the warning will appear automatically.

Calling the API to list blueprints inside the modal dialog code it defiitely a no-go.

@jgiardino since we don't have yet events, I would close this issue, since the current implementation is not that problematic.

The issue will solve itself once we have events introduced.
