### ISSUE TITLE
.pot file contains incorrect locations

### ISSUE THREAD

**Issue by allisonkarlitskaya** [osbuild/cockpit-composer#1323]
The visible name of the main branch has been renamed to "main", but the slug is still "master".  Also, all pages currently show an orange `!` with the error:

> This component is set up incorrectly.
>
> The repository browser URL points to non-existing locations:
>
>    https://github.com/osbuild/cockpit-composer/blob/master/build/messages/components/Modal/PendingChanges.json#L0 (404 Client Error: Not Found for url: https://github.com/osbuild/cockpit-composer/blob/main/build/messages/components/Modal/PendingChanges.json#L0)
>
> This can happen if the path within the translation files contains references to a parent directory, or is absolute.

See here, for example:

https://translate.fedoraproject.org/projects/cockpit-composer/master/

The un-renamed slug can be fixed via Manage → Rename, at least.  I'm not sure what's required to fix the other error.

**Comment by marusak** [comment]
> The un-renamed slug can be fixed via Manage → Rename, at least. 

I have renamed it.

>  I'm not sure what's required to fix the other error.

I don't see any error. But links indeed don't work. Example link is https://github.com/osbuild/cockpit-composer/blob/main/build/messages/pages/blueprintEdit/index.json#L0 because in the [.pot](https://github.com/osbuild/cockpit-composer-weblate/blob/main/cockpit-composer.pot) file locations are generated as `build/messages/pages/blueprintEdit/index.json` while there is not such location. It should be `pages/blueprintEdit/index.js`. This is issue when `.pot` file is being generated.

**Comment by jkozol** [comment]
@marusak Do you have any suggestions on fixing this issue? We extract the translations to a directory when creating the .pot file. This directory won't exist in github.

**Comment by marusak** [comment]
I don't unfortunately. Either you need to look at the tools you are using if they don't support this in some way or use different approach all together.
