### ISSUE TITLE
Date/time in list of Images

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#321]
Currently in the list of images, the list item displays a date with the label "Date Created". This date is currently the date provided by the API, and is the date the compose status was last updated.

Instead, the API will be updated to provide three date/time values:
(per https://github.com/weldr/lorax/issues/409)

- Date/time the compose was put in the queue
- Date/time the compose process was started
- Date/time the compose process was completed

In the UI, these dates would display as listed below:

- [ ] "Added to Queue" (maybe only displays for pending status, depending on how the layout works out)
- [ ] "Build Started" (only displays for statuses other than pending)
- [ ] "Build Finished" (only displays for statuses other than pending)
  - [ ] Nice to have: this would display as a duration, labeled "Build Time"

Additionally:

- [ ] These values should include the time. Cockpit currently uses Moment.js to handle displaying dates/times

**Comment by KKoukiou** [comment]
@jgiardino Is this still valid? I can implement it since the API provides now these values, but I am afraid that they would be weird inside the table row.
If we still want it, pls let me know if I should add it bellow the existing date attribute, or somewhere else.
![Screen Shot 2019-08-02 at 17 47 34](https://user-images.githubusercontent.com/14921356/62382384-bb3da780-b54d-11e9-9dcb-200102dd014c.png)

**Comment by jkozol** [comment]
@jgiardino I don't believe we need any more date information than we currently have.
