### ISSUE TITLE
Missing download blueprint to toml

### ISSUE THREAD

**Issue by atodorov** [osbuild/cockpit-composer#339]
There is an export functionality which gives me a plain text list of RPM packages

Can you please clarify if we are going to have a "Download toml" functionality (or update the export one to match) to make it consistent with composer-cli ?

**Comment by atodorov** [comment]
```
httpd-2.4.*-undefined
mod_auth_kerb-5.4-undefined
mod_ssl-2.4.*-undefined
php-5.4.*-undefined
php-mysql-5.4.*-undefined
openssh-server-7.*-undefined
rsync-3.1.*-undefined
tmux-1.8-undefined
```

This is what I see for the http-server recipe. What are these `undefined` things? probably a separate issue.

**Comment by KKoukiou** [comment]
The undefined in the packages names is not present any more,

![export-welder](https://user-images.githubusercontent.com/14921356/56738988-0d607700-676e-11e9-9b32-ce58534c8a3e.png)

So this issue, is now only about re-implementing the dialog to download  a toml as composer CLI does:
See:
```
# composer-cli blueprints save dev-golang-1
# ls -l dev-golang-1.toml
-rw-r--r--. 1 root root 295 Mar 15 14:38 dev-golang-1.toml
```

@jgiardino @larskarlitski since that's a change in the existing functionality I would like your feedback on this?

**Comment by jgiardino** [comment]
I'm not opposed to adding that functionality in. I'm not sure what the purpose would be for that, though, so I'm not sure how it compares to other priorities. And I'm also not sure how easy or difficult this would be.

**Comment by larskarlitski** [comment]
I'd love to have it, so that I don't have to switch to the command line to export a blueprint. I do this sometimes, because we don't yet expose all blueprint options in the UI.

Not urgent, of course.

**Comment by jkozol** [comment]
@jgiardino @larskarlitski Any thoughts on which export formats we would like the UI to support?

**Comment by jkozol** [comment]
This Is covered by https://issues.redhat.com/browse/COMPOSER-1750
