### ISSUE TITLE
upload image - embedded help for AWS images

### ISSUE THREAD

**Issue by jkozol** [osbuild/cockpit-composer#829]
The following are recomended help texts for the aws image upload wizard steps. These are still WIP.

**Help text to display when the user selects AWS**

> Image Builder can upload images you create to an S3 bucket in AWS and then import them into EC2. When the image build is complete and the upload action is successful, the image file is available in the AMI section of EC2. Most of the values required to upload the image can be found in the [AWS Management Console](https://console.aws.amazon.com/console/home). Also, you must have an **Identity and Access Management (IAM)** role named vmimport.

 **Access key ID**

> You can create and find existing Access key IDs on the **Identity and Access Management (IAM)** page in the AWS console.

 **Secret access key**

> You can find the Secret access key only when you create a new Access key ID on the **Identity and Access Management (IAM)** page in the AWS console.

**AWS Region**

> Provide the.AWS Region where you want to import your image.

**Amazon S3 bucket name**

> Provide the S3 bucket name to which the image file will be uploaded before being imported into EC2. The bucket must already exist in the Region where you want to import your image. You can find a list of buckets on the **S3 buckets** page in the **Amazon S3** storage service in the AWS console.

**Image name**

> Provide a file name to be used for the image file that will be uploaded.

**Comment by jgiardino** [comment]
Thanks for creating this issue. These are great! Here are a couple of suggestions...

- Add "the" to this statement in the first text chunk
  > will be removed from **the** S3 bucket that you specified.

- All instances of "portal" should be replaced with either "console" or "management console". I think saying just "AWS console" in the field level help, and stating the full name in the opening help text (see comment below) would be fine.

- What are your thoughts on adding a statement like this to the end of the first chunk of help text:
  > Most of the values required to upload the image can be found in the [AWS Management Console](https://console.aws.amazon.com/console/home).
  - There were some comments in #781 about including links, but I don't think we should provide links to specific pages, and can just provide a link to the home page of each cloud provider instead.

**Comment by teg** [comment]
> an EC2 instance

Are we sure this is the term we want, rather than just "EC2"?

> and will be removed from the S3 bucket that you specified

This does not currently happen, are we sure this is the behaviour we want?

> Amazon S3 bucket name

We should document that we will not create the bucket, but that it must already exist (in the right region), and must have the right permission set (we need to research exactly what we require here).

**Comment by jgiardino** [comment]
Thanks for the feedback, @teg! 

I'm good with whatever behavior is recommended regarding the S3 bucket. And I'm good with not supporting creation of a bucket.

I'm generally clueless about the "Region" input. We currently associate Region with the authentication inputs instead of the file upload destination. I had included a question about Region in this [comment on the upload PR](https://github.com/weldr/cockpit-composer/pull/767#issuecomment-545635240), but if we don't support creation of a bucket, and only ever use existing buckets, then is region still necessary?

**Comment by teg** [comment]
We should investigate that, but I thought buckets were per region

**Comment by jgiardino** [comment]
Here is a summary of what was discussed in the team chat.

The region seems to be more important in deciding where the image lands in EC2. We should confirm this is the case with the upload feature currently available in osbuild-composer.

The image is first available in the S3 bucket that the user specifies, but then is imported into EC2. The user needs to have the appropriate IAM policy specified for their AWS account for this to happen. We should include some help text in the UI to let the user know that this is the case. It would be good to confirm what happens if this policy isn't correctly set so that we can communicate something to the user, whether via message in Image Builder or with instruction on where to look in AWS and what to expect when the import isth successful or not.

Details about the vm-import policy are provided here, but there seems to be no mention of an IAM policy: https://aws.amazon.com/ec2/vm-import/

**Comment by bcl** [comment]
More details about the settings that need to be configured before an upload/import:
https://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-image-import.html#import-image-prereqs

**Comment by jkozol** [comment]
Thanks for all of the suggestions and feedback. I have updated the help text.

**Comment by jkozol** [comment]
@jgiardino In regards to the names such as `S3 bucket` or `Identity and Access Management (IAM)` is it known which strings should be translated and which shouldn't?

**Comment by jgiardino** [comment]
Regarding your previous question, here are examples of translated strings in AWS:
- Le damos la bienvenida a Identity and Access Management (IAM)
- Bucket creado

Based on how AWS uses these strings, I suggest that we do not translate "Identity and Access Management (IAM)" or "bucket".

As for the help text, here are a couple of suggestions. Let me know if you have alternate thoughts on these...

**Help text to display when the user selects AWS**
_Updated to provide details about `vmimport` in a separate paragraph and also provide more details about why this is important_
> Image Builder can upload images you create to an S3 bucket in AWS and then import them into EC2. When the image build is complete and the upload action is successful, the image file is available in the AMI section of EC2. Most of the values required to upload the image can be found in the AWS Management Console. 
>
> This upload process requires that you have an Identity and Access Management (IAM) role named `vmimport` to ensure that the image can be imported from the S3 bucket into EC2. For more details, refer to the [AWS Required Service Role](https://docs.aws.amazon.com/vm-import/latest/userguide/vmie_prereqs.html#vmimport-role).

**Access key ID**
_No changes made yet, but I'm wondering if we should suggest they copy the secret access key in the event that they create a new access key._
> You can create and find existing Access key IDs on the Identity and Access Management (IAM) page in the AWS console.

**Secret access key**
_Minor change here, changed the "find" to "view"_
> You can view the Secret access key only when you create a new Access key ID on the Identity and Access Management (IAM) page in the AWS console.

**AWS Region**
_Included a second statement to reiterate that this must be the same region as the bucket_
> Provide the AWS Region where you want to import your image. This must be the same region where the S3 bucket exists.

Also, maybe these are separate issues, but leaving these comments here for discussion:
- Can we change the label "Amazon S3 bucket name" to just "Amazon S3 bucket"? Originally, this feature supported the ability to create a new bucket. And in this case, we were asking for a "name" for that bucket. But since that's not the case, I think "name" is implied when we prompt the user to specify an existing S3 bucket.
- The "AWS region" form field should come after the "Amazon S3 bucket" field. This input is less related to authentication and more related to file upload destination, and especially the bucket.
