### ISSUE TITLE
I can't see any Logs when creating an image

### ISSUE THREAD

**Issue by stefwalter** [osbuild/cockpit-composer#974]
### Description of problem

No logs are shown to me during image creation. Just "Running...". Since there is a [Logs] button in the cockpit-composer UI as a user I would have expected to see more detailed information about what the image creation steps / or log output is actually doing.

### Component (web, API, etc)

cockpit-composer

### Version or commit hash (if applicable)

```
osbuild-composer-worker-11-1.fc32.x86_64
cockpit-composer-18-1.fc32.noarch
composer-cli-32.9-1.fc32.x86_64
osbuild-composer-11-1.fc32.x86_64
```

### How often reproducible

Every time

### Steps to Reproduce

1.I've created an (empty see #973) blueprint in cockpit-composer. 
2. Created a QCow2 image using the 'Create Image' dialog.
3. I then clicked on the 'queue' link that was shown to see the image being built.
4. I click the 'Logs' button

### Actual results

![Screenshot from 2020-05-29 11-49-41](https://user-images.githubusercontent.com/795070/83246489-8072c300-a1a2-11ea-9737-a2f6b0e14403.png)

### Expected results

Some detailed logs or progress information of some kind should be shown once I click the Logs button.

**Comment by teg** [comment]
The logs are currently only available when the build has finished (or failed).

I agree that it is not very intuitive the way it is now. I would suggest hiding the `Log` button until logs are available. Thoughts on that @jgiardino and @jkozol?

Long-term, I think we should expose more detailed state from osbuild to show in the UI (something like `PENDING` -> `BUILDING` -> `UPLOADING` -> `REGISTERING` -> `DONE`), and rather de-emphasize the logs even more, as I think they are mostly a development/debugging tool. I'll defer to the UI experts on that though ;)

**Comment by jgiardino** [comment]
Adding @andreasn to this discussion. 

Generally, the best solution when a process is running is to provide a progress bar that provides feedback to the user regarding how far along they are in the process. Feedback about what stage the process is currently in, instead of just a percentage, can also be helpful for users. 

But if that isn't possible, then any information we can provide besides just an indeterminate process indicator (e.g. a spinning icon) would be ideal. So breaking apart the process into separate steps, as @teg suggested, would be helpful. 

Related to this, the prototype that we're currently reviewing presents the following after the user initiates image creation. I don't have number of participants or specific comments yet, but there have been positive comments regarding the availability of logs. If I remember correctly, one participant wanted more specific progress indication, and really doesn't like the spinner icons, but seemed happier that he could view logs to see more details about what was currently happening. 

![image](https://user-images.githubusercontent.com/21063328/83266617-130a6680-a191-11ea-9926-ee10d949f681.png)

@andreasn do you remember anything else (or remember things differently)? We can definitely pull feedback from sessions specific to this into the final report so that we can discuss later, too.

**Comment by teg** [comment]
> You're referring to the usability test on Thursday, right?
> As far as I recall, one of the big motivations for seeing progress for the participant was that the they wanted to make sure things hadn't gotten stuck somewhere in the process, so the more detailed feedback, the better. In the cases where something had gotten stuck or failed complete, they wanted to have something to give to help desk or attach to a support case.

That makes a lot of sense to me.
