### ISSUE TITLE
Continuous Integration on RHEL

### ISSUE THREAD

**Issue by stefwalter** [osbuild/cockpit-composer#977]
### Description of problem

Since cockpit-composer does continuous delivery into RHEL nightlies and CentOS Stream ... Yay!

I noticed we really should be running our CI on this component on RHEL, similar to how Cockpit runs its CI against one or more RHEL versions. This shouldn't be too hard to set up, given that we're using Cockpit's CI systems.

### Component (web, API, etc)

testing

### Version or commit hash (if applicable)

master 6e735255bb114be4ee5687d354aaec6fe3d67bd1

### How often reproducible

Every time.

### Steps to Reproduce

1. Open a pull request.

### Actual results

Notice RHEL is not in the 'checks'

### Expected results

RHEL should be one of the operating systems in the CI list on each pull request.

**Comment by stefwalter** [comment]
CC @martinpitt This should be pretty trivial to do no?

**Comment by martinpitt** [comment]
@stefwalter : Right, and we actually used to have that on master. RHEL was dropped from master PRs due to the impending change from lorax to osbuild. But I suppose now it could be put back for master and fedora-32? @henrywang , @larskarlitski ?

FTR, RHEL tests do run on the rhel8 branch, see https://github.com/cockpit-project/bots/blob/master/task/testmap.py#L147

**Comment by larskarlitski** [comment]
Yeah, I think we can enable this again now that the change is through.

**Comment by henrywang** [comment]
We can close this issue because `rhel-8-3` test scenario is landed by [bots PR](https://github.com/cockpit-project/bots/pull/954) and [land PR](https://github.com/osbuild/cockpit-composer/pull/991).
